#!/bin/sh

[ "$ACTION" = "add" ] || [ "$ACTION" = "ifup" ] || [ "$ACTION" = "register" ] || [ "$ACTION" = "link-up" ] || [ "$ACTION" = "up" ] || [ "$ACTION" = "ifupdate" ] || [ "$ACTION" = "bound" ] || exit

set_interface_rps() {
	local core_mask="$1"
	local interface="$2"

	for d in /sys/class/net/${interface}/queues/rx-*; do
		[ -d $d ] && echo "${core_mask}" > $d/rps_cpus
	done
}

case "$(board_name)" in
embedfire,lubancat-5)
	sleep 15
	echo f0 > /sys/class/net/eth0/queues/rx-0/rps_cpus
	echo f0 > /sys/class/net/eth1/queues/rx-0/rps_cpus
	echo f0 > /sys/class/net/eth0/queues/rx-1/rps_cpus
	echo f0 > /sys/class/net/eth1/queues/rx-1/rps_cpus
	;;
esac
